# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from disco.transports.proto import transport_pb2 as disco_dot_transports_dot_proto_dot_transport__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in disco/transports/proto/transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEvents = channel.stream_unary(
                '/disco.transports.proto.DiscoTransport/SendEvents',
                request_serializer=disco_dot_transports_dot_proto_dot_transport__pb2.EventEnvelopeMsg.SerializeToString,
                response_deserializer=disco_dot_transports_dot_proto_dot_transport__pb2.TransportAck.FromString,
                _registered_method=True)
        self.SendPromise = channel.unary_unary(
                '/disco.transports.proto.DiscoTransport/SendPromise',
                request_serializer=disco_dot_transports_dot_proto_dot_transport__pb2.PromiseEnvelopeMsg.SerializeToString,
                response_deserializer=disco_dot_transports_dot_proto_dot_transport__pb2.TransportAck.FromString,
                _registered_method=True)


class DiscoTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEvents(self, request_iterator, context):
        """Events: potentially large and frequent. Use a client-streaming RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPromise(self, request, context):
        """Promises: always small. Use a unary RPC for better latency and observability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.SendEvents,
                    request_deserializer=disco_dot_transports_dot_proto_dot_transport__pb2.EventEnvelopeMsg.FromString,
                    response_serializer=disco_dot_transports_dot_proto_dot_transport__pb2.TransportAck.SerializeToString,
            ),
            'SendPromise': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPromise,
                    request_deserializer=disco_dot_transports_dot_proto_dot_transport__pb2.PromiseEnvelopeMsg.FromString,
                    response_serializer=disco_dot_transports_dot_proto_dot_transport__pb2.TransportAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'disco.transports.proto.DiscoTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('disco.transports.proto.DiscoTransport', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/disco.transports.proto.DiscoTransport/SendEvents',
            disco_dot_transports_dot_proto_dot_transport__pb2.EventEnvelopeMsg.SerializeToString,
            disco_dot_transports_dot_proto_dot_transport__pb2.TransportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPromise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disco.transports.proto.DiscoTransport/SendPromise',
            disco_dot_transports_dot_proto_dot_transport__pb2.PromiseEnvelopeMsg.SerializeToString,
            disco_dot_transports_dot_proto_dot_transport__pb2.TransportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
